wandb:
  project: imp_est 
  exp_num: 1
path:
  data_file_name: df/csv
  checkpoint_path: checkpoints
model:
  d_model: 768
  n_classes: 2
  nhead: 5
  ntimes: 5
  dim_feedforward: 2048
  dropout: 0.4
  activation: gelu
  layer_norm_eps: 0.00001
  max_length: 144
training:
  test_size: 0.3
  n_epochs: 30
  batch_size: 128
  max_length: 144
  learning_rate: 0.005
  text_column_name: text
  label_column_name: label
callbacks:
  patience: 5
  patience_min_delta: 0
